services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - uitfa

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - uitfa

  model:
    image: bthzang/uitfa-model:latest
    restart: always
    ports:
      - 8002:8000
    networks:
      - uitfa

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - uitfa
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  db:
    driver: local

networks:
  uitfa:
    driver: bridge
